forge "https://forgeapi.puppetlabs.com"

#moduledir '/tmp/packer-puppet-masterless/module-0'

mod 'puppetlabs/apache', :latest
mod 'puppetlabs/mysql', :latest
mod 'fsalum/newrelic', :latest
mod 'puppetlabs/rabbitmq', :latest
mod 'ajcrowe/supervisord', :latest

#mod 'treeherder',
#    :git => "https://github.com/klibby/treeherder-infra/puppet",
#    :branch => 'buildtest'

# flower/nginx
# vcsrepo?
