forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/mysql'
mod 'fsalum/newrelic'
mod 'puppetlabs/rabbitmq'
mod 'ajcrowe/supervisord'

mod 'mozilla/treeherder',
    :git => "https://github.com/klibby/treeherder-infra.git",
    :ref => 'buildtest',
    :path => "puppet/modules"

# flower/nginx
# vcsrepo?
